apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-monitoring
resources:
  - eso-sa.yaml
  - external-secret.yaml
  - secretstore.yaml
  # - test-critical-alert.yaml
