apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gsm-secret-store
  namespace: openshift-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: 30s
  provider:
    gcpsm:
      projectID: okd-homelab
      auth:
        workloadIdentityFederation:
          audience: //iam.googleapis.com/projects/1086456784694/locations/global/workloadIdentityPools/okd-pool/providers/okd-provider
          serviceAccountRef:
            name: external-secrets
            namespace: openshift-monitoring
            audiences:
              - openshift
