apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webserver-ingress
  namespace: webserver
spec:
  ingressClassName: nginx
  rules:
  - host: webserver.homelab.jenniferpweir.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: webserver-service
            port:
              number: 80
