apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - customresourcedefinition.yaml
  - daemonset.yaml
  - deployment-longhorn-driver-deployer.yaml
  - deployment-longhorn-ui.yaml
  - namespace.yaml
  - priorityclass.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml
