apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: pihole
resources:
  - configmap.yaml
  - dns-service.yaml
  - headless-service.yaml
  - namespace.yaml
  - statefulset.yaml
  - web-service.yaml
