apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole
  namespace: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  serviceName: pihole
  replicas: 1
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:2025.11.1@sha256:91dc91ddd413bf461c283204558f8f21839851e9824799075a7ceff7c77eea40
          lifecycle:
            postStart:
              exec:
                command: ["sh", "-c", 'sleep 10 && echo "" | pihole setpassword && pihole-FTL --config misc.etc_dnsmasq_d true'] # disable password and enable dnsmasq for wildcard dns
          envFrom:
            - configMapRef:
                name: pihole-configmap
            - configMapRef:
                name: pihole-wildcard-configmap
          ports:
            - name: svc-80-tcp-web
              containerPort: 80
              protocol: TCP
            - name: svc-53-udp-dns
              containerPort: 53
              protocol: UDP
            - name: svc-53-tcp-dns
              containerPort: 53
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: svc-80-tcp-web
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: svc-53-tcp-dns
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: pihole-etc-pihole
              mountPath: /etc/pihole
            - name: pihole-etc-dnsmasq
              mountPath: /etc/dnsmasq.d
            - name: wildcard-config
              mountPath: /etc/dnsmasq.d/02-my-wildcard-dns.conf
              subPath: 02-my-wildcard-dns.conf
              readOnly: true
      volumes:
        - name: wildcard-config
          configMap:
            name: pihole-wildcard-configmap
  volumeClaimTemplates:
    - metadata:
        name: pihole-etc-pihole
        namespace: pihole
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: <storageClassName>
        resources:
          requests:
            storage: 3Gi
    - metadata:
        name: pihole-etc-dnsmasq
        namespace: pihole
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: <storageClassName>
        resources:
          requests:
            storage: 3Gi
