apiVersion: operator.openshift.io/v1 # operator.openshift.io/v1 for editable operator configs and config.openshift.io/v1 for cluster snapshot configs
kind: Console
metadata:
  annotations:
    capability.openshift.io/name: Console
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  customization:
    capabilities:
    - name: LightspeedButton
      visibility:
        state: Enabled
    - name: GettingStartedBanner
      visibility:
        state: Enabled
    customLogoFile:
      name: ""
    developerCatalog:
      types:
        state: Enabled
    perspectives:
    - id: admin
      visibility:
        state: Enabled
    - id: dev
      visibility:
        state: Enabled
  ingress:
    clientDownloadsURL: ""
    consoleURL: ""
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  plugins:
  - networking-console-plugin
  - monitoring-plugin
  - kubevirt-plugin
  route:
    hostname: ""
    secret:
      name: ""
  unsupportedConfigOverrides: null
