apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/instance: nginx-gateway
    app.kubernetes.io/name: nginx-gateway
    app.kubernetes.io/version: 2.3.0
  name: nginx-gateway-cert-generator
  namespace: nginx-gateway
spec:
  template:
    metadata:
      annotations: null
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - generate-certs
            - --service=nginx-gateway
            - --cluster-domain=cluster.local
            - --server-tls-secret=server-tls
            - --agent-tls-secret=agent-tls
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ghcr.io/nginx/nginx-gateway-fabric:2.3.0
          imagePullPolicy: IfNotPresent
          name: cert-generator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsUser: 101
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Never
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
      serviceAccountName: nginx-gateway-cert-generator
  ttlSecondsAfterFinished: 30
