apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - customresourcedefinition.yaml
  - deployment-nginx-gateway.yaml
  - gatewayclass.yaml
  - gateway-api-crds.yaml
  - job.yaml
  - namespace.yaml
  - nginxgateway.yaml
  - nginxproxy.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml
