apiVersion: gateway.nginx.org/v1alpha1
kind: NginxGateway
metadata:
  labels:
    app.kubernetes.io/instance: nginx-gateway
    app.kubernetes.io/name: nginx-gateway
    app.kubernetes.io/version: 2.3.0
  name: nginx-gateway-config
  namespace: nginx-gateway
spec:
  logging:
    level: info
