apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: nginx-gateway
    app.kubernetes.io/name: nginx-gateway
    app.kubernetes.io/version: 2.3.0
  name: nginx-gateway-cert-generator
  namespace: nginx-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-gateway-cert-generator
subjects:
  - kind: ServiceAccount
    name: nginx-gateway-cert-generator
    namespace: nginx-gateway
