apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
patches:
  - target:
      kind: PersistentVolumeClaim
      name: grafana-pvc
    patch: |-
      - op: add
        path: /spec/storageClassName
        value:
          rook-ceph-block-replicated
