apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: v5
  installPlanApproval: Manual # oc patch installplan install-xxxxx -n grafana-operator --type merge --patch '{"spec":{"approved":true}}'
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: grafana-operator.v5.20.0
