apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: 1.33.1
controlPlaneEndpoint: "k8scp:6443"
networking:
  podSubnet: 10.200.0.0/16
  # podSubnet: 192.168.0.0/16

Pod CIDR:     10.200.0.0/16
Service CIDR: 10.201.0.0/16
