apiVersion: v1
kind: ConfigMap
metadata:
  name: google-creds
  namespace: argocd
data:
  credentials.json: |
    {
      "type": "external_account",
      "audience": "//iam.googleapis.com/projects/1086456784694/locations/global/workloadIdentityPools/okd-pool/providers/okd-provider",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "/var/run/secrets/openshift/serviceaccount/token",
        "format": {
          "type": "text"
        }
      },
      "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/gsm-accessor@okd-homelab.iam.gserviceaccount.com:generateAccessToken"
    }
