apiVersion: v1
kind: ServiceAccount # create this SA since argo doesnt create one for repo server by default
metadata:
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
  name: argocd-argocd-repo-server
  namespace: argocd
imagePullSecrets:
  - name: quay-jennweir-pull-secret
