apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: okd
rendezvousIP: 192.168.0.11
hosts:
  - hostname: cp-1
    role: master
    interfaces:
      - name: eno1
        macAddress: 18:60:24:f8:a7:87
    networkConfig:
      interfaces:
        - name: eno1
          type: ethernet
          state: up
          mac-address: 18:60:24:f8:a7:87
          ipv4:
            enabled: true
            address:
              - ip: 192.168.0.11
                prefix-length: 23
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.0.236
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.0.1
            next-hop-interface: eno1
            table-id: 254
  - hostname: cp-2
    role: master
    interfaces:
      - name: eno1
        macAddress: 18:60:24:f6:24:5b
    networkConfig:
      interfaces:
        - name: eno1
          type: ethernet
          state: up
          mac-address: 18:60:24:f6:24:5b
          ipv4:
            enabled: true
            address:
              - ip: 192.168.0.12
                prefix-length: 23
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.0.236
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.0.1
            next-hop-interface: eno1
            table-id: 254
  - hostname: cp-3
    role: master
    interfaces:
      - name: eno1
        macAddress: 18:60:24:e8:a3:30
    networkConfig:
      interfaces:
        - name: eno1
          type: ethernet
          state: up
          mac-address: 18:60:24:e8:a3:30
          ipv4:
            enabled: true
            address:
              - ip: 192.168.0.13
                prefix-length: 23
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.0.236
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.0.1
            next-hop-interface: eno1
            table-id: 254
