kind: Secret
apiVersion: v1
metadata:
  name: azure-client-secret
  namespace: openshift-config
type: Opaque
stringData:
  clientSecret: <path:projects/648542105177/secrets/azure_client_secret#azure_client_secret>
