# https://github.com/okd-project/okd/releases
apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: next-scos-4
  clusterID: <path:projects/1086456784694/secrets/okd_cluster_id#okd_cluster_id>
  desiredUpdate:
    force: false
    image: quay.io/okd/scos-release@sha256:3bb6f10c2e39a9378237053ae97c72227af188ad8c89cb709e3d631b0fc0fa32
    version: 4.21.0-okd-scos.ec.8
  upstream: https://amd64.origin.releases.ci.openshift.org/graph
