# https://github.com/okd-project/okd/releases
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
  metadata:
    name: version
  spec:
    channel: stable-scos-4
    clusterID: <path:projects/1086456784694/secrets/okd_cluster_id#okd_cluster_id>
    desiredUpdate:
      force: false
      image: quay.io/okd/scos-release@sha256:d4b32427fae231d75e72dd8b265efe76e045dde7c9be4075a2023bb054ce5744
      version: 4.21.0-okd-scos.ec.7
    upstream: https://amd64.origin.releases.ci.openshift.org/graph
kind: List
metadata: {}