# https://github.com/okd-project/okd/releases
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
  metadata:
    name: version
  spec:
    channel: stable-scos-4
    clusterID: <path:projects/1086456784694/secrets/okd_cluster_id#okd_cluster_id>
    desiredUpdate:
      force: false
      image: quay.io/okd/scos-release@sha256:0967ff565fc3610f7a62ddde3b43f27906538a45648c780a630fce8e4bbc422b
      version: 4.20.0-okd-scos.6
    upstream: https://amd64.origin.releases.ci.openshift.org/graph
kind: List
metadata: {}