# https://github.com/okd-project/okd/releases
apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: next-scos-4
  clusterID: <path:projects/1086456784694/secrets/okd_cluster_id#okd_cluster_id>
  desiredUpdate:
    force: false
    image: quay.io/okd/scos-release@sha256:a303ecbfab19d1d98d2258efde3b43cac4c308bedff49e3c10a27314b70dfe37
    version: 4.21.0-okd-scos.ec.13
  upstream: https://amd64.origin.releases.ci.openshift.org/graph
