apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gsm-secret-store
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  serviceAccountRef:
    name: external-secrets
    namespace: cert-manager
  audience: //iam.googleapis.com/projects/1086456784694/locations/global/workloadIdentityPools/okd-pool/providers/okd-provider
  externalTokenEndpoint: https://storage.googleapis.com/jennweir-homelab
