apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gsm-secret-store
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    gcpsm:
      projectID: okd-homelab
      auth:
        workloadIdentityFederation:
          audience: //iam.googleapis.com/projects/1086456784694/locations/global/workloadIdentityPools/okd-pool/providers/okd-provider
          serviceAccountRef:
            name: external-secrets
            namespace: cert-manager
            audiences:
              - openshift
